#pragma once
enum global_error_code {
    QNX_SCREEN_DISPLAY_COUNT_LACK = -1000,
    QNX_SCREEN_DISPLAY_NOT_FOUND = -1001,
    DISPLAY_MARGIN_COORDINATE_INVALID = -1002,
    DISPLAY_MARGIN_COORDINATE_EXCEED = -1003,
    IMAGE_FORMAT_INVALID = -1004,
    IMAGE_PTR_IS_NULL = -1005,
};